### ISSUE TITLE
Sort, Filter, Grouping option for the result list on the website (or an export)

### ISSUE THREAD

**Issue by LokiMidgard** [aidatatools/ollama-benchmark#18]
It would be nice if the table on the website had more formating options. alternativly an export as  csv would be nice, so it can be imported in tools.

**Comment by burpeenerd** [comment]
+1

**Comment by chuangtc** [comment]
It's done by checkbox for filtering selected models.
<img width="1027" alt="Screenshot 2024-12-30 at 6 15 15 AM" src="https://github.com/user-attachments/assets/2b9909cb-6b81-41ae-9e21-bd18d484f47f" />
