### ISSUE TITLE
flag for ollama executable path

### ISSUE THREAD

**Issue by K1ngjulien** [aidatatools/ollama-benchmark#3]
Hi!

Nice work! Could you add a flag like `--ollama-bin ~/code/ollama/ollama` to explicitly give the path to the ollama executable?

when building and testing ollama from source, i'd like to just be able to supply it the path, without having to do a full install on the system.

Cheers

**Comment by chuangtc** [comment]
--ollamabin flag is added in v0.3.12
Please checkout the latest code
