### ISSUE TITLE
Add check for required package lsb-core on linux

### ISSUE THREAD

**Issue by felixboettger** [aidatatools/ollama-benchmark#5]
In the systeminfo module, lsb_release may be called as a subprocess. The lsb_release command is part of the lsb-core package, which is not installed by default on some distributions. This causes the benchmark to fail with TypeError: 'NoneType' object is not subscriptable.

Consider adding a try-catch block:

```
try:  
    r2 = subprocess.run(['lsb_release','-a'],capture_output=True,text=True)   
except Exception as e:     
    print("lsb-core is required")     
```

**Comment by chuangtc** [comment]
Could you try to install llm-benchmark with the following command on your Debian Linux?
```bash
pip install llm-benchmark==0.3.15
```
