### ISSUE TITLE
feat: Add llama 3 models

### ISSUE THREAD

**Issue by sammcj** [aidatatools/ollama-benchmark#7]
It would be good to replace llama 2 with llama 3 as 2 is a very old model now.

**Comment by sammcj** [comment]
By the way, I was able to modify the code myself to run against llama 3, I just didn't want to submit a PR without knowing the impact to your existing data.

You can see my results in: https://llm.aidatatools.com/results-macos.php?sort=false 😉

**Comment by chuangtc** [comment]
Thanks for your suggestions. Please use the latest 0.3.18 version
```bash
pip install llm-benchmark==0.3.18
llm_benchmark run
```
If it's done, please help close the ticket.
Thank you.

**Comment by sammcj** [comment]
Oh wow that was quick!

Thank you.

```
llm_benchmark run                                                                 (sam)
----------Apple Mac---------
Total memory size : 96.00 GB
cpu_info: Apple M2 Max
gpu_info: Apple M2 Max
os_version: macOS 14.4.1 (23E224)
ollama_version: v0.1.33-rc5-30-g4e82cbc8
----------
LLM models file path：/Users/samm/git/ollama-benchmark-fork/.venv/lib/python3.12/site-packages/llm_benchmark/data/benchmark_models_16gb_ram.yml
Checking and pulling the following LLM models
gemma:2b
gemma:7b
mistral:7b
llama3:8b
phi3:3.8b
llava:7b
llava:13b
----------
```

**Comment by chuangtc** [comment]
For Security and Privacy reason to protect developers. Hiding the details.
